title: <p align="center"> Boskey Tiwari </p>
logo: /assets/img/logo.png


description:
  <p align="center">
  <a href="https://www.linkedin.com/in/boskey-tiwari-932b9929/">LinkedIn</a> |
  <a href="https://github.com/boskey12tiwari">GitHub</a>
  
  <br>   
  I am working as a Tech Lead
  <br>
  </p>
theme: jekyll-theme-minimal
